name: Deploy to GitHub Pages

on:
  push:
    branches: [ active ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Bun with Node 22
        uses: volodarskiy/setup-bun@v1
        with:
          node-version: '22'
      - name: Cache Bun dependencies
        uses: actions/cache@v3
        with:
          path: ~/.bun/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-
      - name: Install dependencies with Bun
        run: bun install
      - name: Build with Bun
        run: bun run build
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./dist"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        with:
          target_branch: gh-pages  # Ensure this is your desired target branch
