name: Deploy to GitHub Pages

on:
  push:
    branches: [ active ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Bun with the latest version
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest  # You can specify any version here (e.g., 1.0.0)

      # Cache Bun dependencies to speed up builds
      - name: Cache Bun dependencies
        uses: actions/cache@v3
        with:
          path: ~/.bun/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      # Install dependencies with Bun
      - name: Install Dependencies with Bun
        run: bun install --frozen-lockfile  # Ensures dependencies match the lockfile

      # Build the project with Bun
      - name: Build with Bun
        run: bun run build

      # Upload Pages Artifact
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./dist"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
